Adding external allocation example
inmanta/examples pull request #1
Opened 2021-05-25 12:01 UTC by edvgui

# In this MR
Created a sample project using a single module (`test_module`).  This module has one service: `VlanService`, which has two vlan_id attributes and uses allocation to populate them.  The allocation is done using an external allocator mock, which relies on a simple file to store already used vlans and as well as the ones available.  The deallocation is done using a resource, `VlanDeallocation`, which takes as attribute `allocation_key`, a reference to the vlan to cleanup passed by the allocator and saved in the service attributes up to the cleanup point.

2021-05-25 12:03 UTC, edvgui commented
Some questions for this:
- Do I need to add test cases for this?
- For this bit I am not sure what I should do:
    > we de-allocate after a failed allocation (we already allocated some attributes, but not all of them)
- How much documentation does it require?

2021-05-25 12:14 UTC, wouterdb requested changes

2021-05-25 12:14 UTC, wouterdb commented on external-allocation/libs/test_module/model/_init.cf
> +        allocation_key=self.north_vlan_allocation_key,
either `vlan_allocation_key` could be null or unset, I think an if statement is required.

2021-05-25 12:14 UTC, wouterdb commented on external-allocation/main.cf
> +import test_module
a readme on the project would be good

2021-05-25 12:16 UTC, wouterdb commented
On the questions:

- Do I need to add test cases for this?
   - Only the most basic 

- For this bit I am not sure what I should do:
   - see comment
 
- How much documentation does it require?
  - Very clear docs on the context (what is this an example of), how to run it, reference to the lsm docs, what are the main mechanisms in here, docs in the code to make it readable.

2021-05-25 12:18 UTC, wouterdb commented on external-allocation/libs/test_module/plugins/__init__.py
> +AllocationSpec(
The extra thingy from the SiriusRootAllocator that causes it to flush-on-failure should also be in here to be complete.

2021-05-25 12:36 UTC, edvgui commented on external-allocation/libs/test_module/model/_init.cf
> +        allocation_key=self.north_vlan_allocation_key,
Done in https://github.com/inmanta/examples/pull/1/commits/ae6764f766cfe878330b1b630cea207ea1099741

2021-05-25 13:08 UTC, edvgui commented on external-allocation/main.cf
> +import test_module
Done in https://github.com/inmanta/examples/pull/1/commits/4692f371f5d4a563efde95bf8686d38c7d8c4598

2021-05-25 15:22 UTC, wouterdb requested changes

2021-05-25 15:22 UTC, wouterdb commented on external-allocation/libs/test_module/plugins/__init__.py
> +    def allocate_for(
The eager flushing is not in yet?

2021-05-26 07:22 UTC, wouterdb requested changes

2021-05-26 07:22 UTC, wouterdb commented on external-allocation/libs/test_module/plugins/__init__.py
> +        # If an error occurred, we first free all the allocated vlans then raise it.
Nice, but not super robust in case of communications failures. 
(if the inventory is unreachable, we will leak) 

I would be good to also add the code for flushing to the server here as well.

2021-05-26 07:46 UTC, edvgui commented on external-allocation/libs/test_module/plugins/__init__.py
> +        # If an error occurred, we first free all the allocated vlans then raise it.
Is this what you mean? https://github.com/inmanta/examples/pull/1/commits/b032b8d05a416949bde4164f2e69624ff2935a7e

2021-05-26 07:50 UTC, wouterdb requested changes

2021-05-26 07:50 UTC, wouterdb commented on external-allocation/libs/test_module/plugins/__init__.py
> +                client = SyncClient("client")
```suggestion
                client = SyncClient("compiler")
```

2021-05-26 07:54 UTC, edvgui commented on external-allocation/libs/test_module/plugins/__init__.py
> +                client = SyncClient("client")
Indeed, fixed it in https://github.com/inmanta/examples/pull/1/commits/e4e52574f5eec23476569ac58c3c51ed504ee1c3

2021-05-26 07:54 UTC, wouterdb approved these changes

2021-05-26 07:55 UTC, merged