added more examples
inmanta/examples pull request #2
Opened 2021-05-27 08:23 UTC by wouterdb

- moved the existing example into the lsm folder
- Added readme's
- Added two variations of an example 

# Questions from the reviewers:

- What do we intend to do testing-wise in this repo? (just a simple compile of the project or more?)
- Is this clear?

2021-05-27 08:25 UTC, bartv reviewed
I am not sure creating multiple levels will improve things. I do think it is a good idea to add lsm to it, like lsm-external-allocation

2021-05-27 08:46 UTC, edvgui reviewed
I think testing what we are trying to show (so more than a simple model compile) would be nice.  Not sure how we should structure those in the ci though.  One Jenkins file for the whole repository would probably grow really big.  Unless our tests are standard enough.

Looks clear to me.  As a tradeoff between folder and prefix, what about keeping the folders (make navigation on github easier if you know where to find it, but finding it the first time less easy), but add an index (with links) in the main readme that doesn't follow the folder structure (so with prefixes for example) to make it easier finding it the first time.

2021-05-27 08:46 UTC, edvgui commented on README.md
> +1. LSM: examples related to Lifecycle and Service Management, these examples require a commercial license.
```suggestion
1. [LSM](lsm/README.md): examples related to Lifecycle and Service Management, these examples require a commercial license.
```

2021-05-27 08:54 UTC, bartv commented
> I think testing what we are trying to show (so more than a simple model compile) would be nice. Not sure how we should structure those in the ci though. One Jenkins file for the whole repository would probably grow really big. Unless our tests are standard enough.
> 
> Looks clear to me. As a tradeoff between folder and prefix, what about keeping the folders (make navigation on github easier if you know where to find it, but finding it the first time less easy), but add an index (with links) in the main readme that doesn't follow the folder structure (so with prefixes for example) to make it easier finding it the first time.

For testing I would say the each project folder should contain a test.sh and that is it

2021-05-27 13:59 UTC, wouterdb commented on README.md
> +1. LSM: examples related to Lifecycle and Service Management, these examples require a commercial license.
applied in main index.

2021-05-27 14:00 UTC, wouterdb commented
@bartv a `test.sh` that assumes inmanta is already installed or not?

2021-05-27 14:06 UTC, bartv commented
> @bartv a `test.sh` that assumes inmanta is already installed or not?

yes, we have to define something like:

- latest iso release is installed and compiler is available

2021-05-27 14:07 UTC, bartv commented
> > @bartv a `test.sh` that assumes inmanta is already installed or not?
> 
> yes, we have to define something like:
> 
>     * latest iso release is installed and compiler is available

The goal for me is not that others can easily run it but that it does not bit root because for example a deprecated syntax or feature is used

2021-05-27 14:09 UTC, edvgui requested changes

2021-05-27 14:09 UTC, edvgui commented on README.md
> +2. [lsm-from-inventory-](lsm-from-inventory-a/README.md): example on how to load all attributes of a service from an external inventory
```suggestion
2. [lsm-from-inventory-a](lsm-from-inventory-a/README.md): example on how to load all attributes of a service from an external inventory
3. [lsm-from-inventory-b](lsm-from-inventory-b/README.md): another example on how to load all attributes of a service from an external inventory
```

2021-05-28 13:24 UTC, bartv approved these changes

2021-05-28 13:25 UTC, edvgui approved these changes

2021-05-28 13:43 UTC, merged