Dariush/training
inmanta/examples pull request #26
Opened 2022-09-21 16:29 UTC by DariushMoh

# Description

* vylab (vyos) project and main.cf done for each step of training until entity model *
* srlab (srlinux) project and main.cf done for each step of training until entity model * 
* Client_setup script created to automatically setup the clients ip and routing table (see README) *

# Reviewers list 

- [x] @edvgui or @wouterdb 

# Self Check:

- [x] Vyos models compiles and are deployed successfully, the routing table are correct and the clients can reach other.
- [x] Srlinux models compiles and are deployed successfully, the routing table are correct and the clients can reach other.

2022-09-22 07:38 UTC, edvgui commented on Training/topology_srlinux.clab.yml
> +        - ./resources/Clients/:/opt/
You mount this very nice script in the container, but don't use it in the startup command, why?

2022-09-22 08:03 UTC, DariushMoh commented on Training/topology_srlinux.clab.yml
> +        - ./resources/Clients/:/opt/
Because the interface eth1 is never created when I run the script and clab basically throw an error `ERRO[0003] failed to run postdeploy task for node C1: failed to Statfs "/proc/41399/ns/net": no such file or directory `.

2022-09-22 09:53 UTC, edvgui commented on Training/topology_srlinux.clab.yml
> +        - ./resources/Clients/:/opt/
Did you try to add a delay? Or to wait for the interface to show up? When the container is started, the interface is not yet in there, and is not named `eth1`, but at some point it will be there, and get that name, you could simply wait for that to happen

2022-09-22 18:40 UTC, wouterdb requested changes
Very nice, I have some detail comments 

1. I would number the files, so the order is clear

2022-09-22 18:40 UTC, wouterdb commented on Training/README.md
> +## 5. Setup the clients
The first thing this file should contain is an overview of what is in this folder. 

e.g.

```markdown
This folder contains examples that are part of the inmanta training program. 

It contains
-  all resources required to set up a lab, consisting of 4 routers in a full mesh topology. This lab and all associated resources exists for both vyos and sros routers. 

<add picture of the lab>
<add link to setup docs>

- an inmanta project to configure
   - the loopback ip on each router
   - all interfaces on the router
   - OSPF on all routers
- different variations of this same model, that become increasingly sophisticated. Each subsequent vesion has less code and more power.  This approach is similar to the one taken in this series of videos (<link to youtube>)

<table of all versions of the main file>
```

2022-09-22 18:40 UTC, wouterdb commented on Training/project/srlab/main.cf
> +First raw configuration of the network, this configuration is uncomplete because yang is really verbose.
I would formulate it more precise and more positive, by saying: 

```suggestion
First version of the model. This example only configures the routers `R1` and `R2` and the interfaces between them, yang is really verbose.

The later models will do the complete configuration

```

2022-09-22 18:40 UTC, wouterdb commented on Training/project/srlab/main_entity_improved.cf
> +This model improves the previous entity based model by reducing free variables and redunduncy. It changes the model view by moving the interfaces in new OspfPeers entities.
```suggestion
This model improves the previous entity based model by reducing free variables and redundancy. It changes the model view by moving the interfaces in new OspfPeers entities.
```

2022-09-22 18:40 UTC, wouterdb commented on Training/project/srlab/main_entity_improved.cf
> +entity OspfPeers:
I prefer the name 'PeerNetwork'

2022-09-22 18:40 UTC, wouterdb commented on Training/project/srlab/main_entity_improved.cf
> +        area_id = "0.0.0.0",
Someone with more network knowledge should review this, e.g. @Pouriya-Inmanta

2022-09-22 18:40 UTC, wouterdb commented on Training/project/srlab/main_entity_improved.cf
> +entity OspfPeer:
I like this entity, but it could have a better name and more documentation 

1. I think OspfPeerInterface might be a better name. 
2. Purely, for training purposes, I would not add two layers of indirection at once, so I would first add the one where this entity doesn't exist.

2022-09-22 18:40 UTC, wouterdb commented on Training/project/srlab/main_entity_improved.cf
> +Router.ospf_peering [0:] -- OspfPeers.routers [2]
Why is this relation here? I think this model structure doesn't require it?

2022-09-22 18:40 UTC, wouterdb commented on Training/project/vylab/main.cf
> +#    area=1,
everything goes into area 0, I think

2022-09-22 18:40 UTC, wouterdb commented on Training/project/vylab/main.cf
> +### r1 area 0 (eth1)
Why is this commented out?

2022-09-22 18:40 UTC, wouterdb commented on Training/project/vylab/main_entity_improved.cf
> +)
The stub networks towards the clients are missing, so ping will not work

2022-09-22 18:40 UTC, wouterdb commented on Training/project/vylab/main_vyos_tunnel.cf
> +Raw configuration of the GRE Tunnel (only works in the old lab with namespaces)
I would remove this, as it doesn't work in docker.

2022-09-23 07:13 UTC, DariushMoh commented on Training/topology_srlinux.clab.yml
> +        - ./resources/Clients/:/opt/
Yes I try to do it in my bash script in `Training/resources/Clients/config_ip` with a while loop, maybe I'm doing something wrong ?

2022-09-23 07:45 UTC, Pouriya-Inmanta commented on Training/project/srlab/main_entity_improved.cf
> +        area_id = "0.0.0.0",
The model looks fine. Just one suggestion, although ordering does not matter in Inmanta compiler, it is better to design your model in a bottom-up way. e.g. first take care of your physical interfaces, then virtual ones (loopback, svi, irb, etc) then go for a bare OSPF config, after that if necessary, OSPF redistribution, etc.

Very nice job!

2022-09-23 12:24 UTC, DariushMoh commented on Training/project/vylab/main_vyos_tunnel.cf
> +Raw configuration of the GRE Tunnel (only works in the old lab with namespaces)
I remove the entire file then ?

2022-09-23 13:01 UTC, DariushMoh commented on Training/project/srlab/main_entity_improved.cf
> +Router.ospf_peering [0:] -- OspfPeers.routers [2]
Because in the `OspfPeer` implementation I need the `router_net_instance` and the `router_ospf_area` objects created in the Router implementation so I expose them with relations. Maybe not the cleanest way to achieve that.

2022-09-23 14:57 UTC, DariushMoh commented on Training/project/srlab/main_entity_improved.cf
> +        area_id = "0.0.0.0",
Thank you I will modify the model to fit your advice.

2022-09-26 11:28 UTC, wouterdb commented on Training/project/vylab/main_vyos_tunnel.cf
> +Raw configuration of the GRE Tunnel (only works in the old lab with namespaces)
yes

2022-09-29 10:47 UTC, wouterdb approved these changes

2022-09-30 08:18 UTC, edvgui commented on Training/topology_srlinux.clab.yml
> +        - ./resources/Clients/:/opt/
It was indeed not as trivial as I thought, I had to dig a little bit, but changing things like this should work:
[config_ip.txt](https://github.com/inmanta/examples/files/9682156/config_ip.txt)

And you also have to change the command and the entrypoint like this:
```yml
    C1:
      kind: linux
      image: praqma/network-multitool:latest
      mgmt_ipv4: 10.0.0.205
      entrypoint: /bin/bash
      cmd: /opt/config_ip 10.0.1.2 eth1 10.0.1.1 30
      binds:
        - ./resources/Clients/:/opt/
```

2022-10-04 09:19 UTC, edvgui approved these changes

2022-10-04 09:19 UTC, merged