Port srlinux to lsm quickstart
inmanta/examples pull request #31
Opened 2022-12-15 16:35 UTC by jptrindade

Updated the lsm quickstart to use SR Linux.
The InterfaceIPAssignment update is still not working. It creates a new instance instead of updating.

The documentation related to this example can be found here: https://github.com/inmanta/lsm/pull/556

The README.md might be outdated as well.

2022-12-16 08:27 UTC, wouterdb requested changes

2022-12-16 08:27 UTC, wouterdb commented on lsm-srlinux/README.md
> +In case of choosing the `containerlab` option, it is worthwhile to mention that you need to have a `SR Linux` Docker image present on the host machine running `containerlab` and having it **tagged**
it is not automatically downloaded? 

If it is, I would drop line 27 up until 35, it just causes confusion.

2022-12-16 08:27 UTC, wouterdb commented on lsm-srlinux/README.md
> +Inmanta [Service Orchestrator](https://inmanta.com/service-orchestrator/) is another containerized piece that can supply a GUI, providing many useful information such as deployment process, agents st
I would drop this entire sub-section, as it doesn't really provide any concrete information and it happens automatically anyways.

2022-12-16 08:27 UTC, wouterdb commented on lsm-srlinux/containerlab/.topology.yml.bak
> +name: srlinux
why is this .bak file in here?

2022-12-16 08:27 UTC, wouterdb commented on lsm-srlinux/README.md
> +# SR Linux Module
About this File:

1. This is purely an introduction to srlinux, nothing is said about lsm? I think it doesn't introduce the content very well.  
2. it uses the open source container, which doesn't have lsm at all, it doesn't mention how to replace the token, ... 
3. I think this can be a copy of the quickstart, as it exists in the https://github.com/inmanta/lsm/pull/556,  (with a link to that content in the docs, when it is merge)
4. @bartv shouldn't we group all lsm things in a folder?

2022-12-16 08:27 UTC, wouterdb commented on lsm-srlinux/main.cf
> +    interface = srlinux::Interface(
if you set `comanaged=false` on the interface or the sub interface, the update will work....

2022-12-16 09:24 UTC, jptrindade commented on lsm-srlinux/README.md
> +# SR Linux Module
I'll wait to change this until we have a final version of the quickstart.

2022-12-22 13:46 UTC, bartv approved these changes

2022-12-22 14:18 UTC, wouterdb requested changes

2022-12-22 14:18 UTC, wouterdb commented on lsm-srlinux/README.md
> +**Make sure that you have the necessary sensitive information**, namely:
```suggestion
**Make sure that you have the necessary license information**, namely:
```

2022-12-22 14:18 UTC, wouterdb commented on lsm-srlinux/README.md
> +    [quickstart prerequisites](https://docs.inmanta.com/inmanta-service-orchestrator/5/quickstart.html#prerequisites) until step 4
```suggestion
    [quickstart prerequisites](https://docs.inmanta.com/inmanta-service-orchestrator/latest/quickstart.html#prerequisites) until step 4
```

2022-12-22 14:18 UTC, wouterdb commented on lsm-srlinux/README.md
> +3.  Change the \<token\> in the repo url to the password that you
It is not clear this refers to the `Credentials to the package repository` from the perquisites section.

2022-12-22 14:18 UTC, wouterdb commented on lsm-srlinux/README.md
> +1.  Follow the
I think it makes more sense to copy paste the setups here, entirely, to improve copy-paste-ability of the instructions

2022-12-22 14:18 UTC, wouterdb commented on lsm-srlinux/README.md
> +    ÃŽnterfaceIPAssignment entity defines four attributes: router\_ip,
Weird character here?

2022-12-22 14:18 UTC, wouterdb commented on lsm-srlinux/README.md
> +    ÃŽnterfaceIPAssignment entity defines four attributes: router\_ip,
All source code strings should be quoted to get the right style, applies to all the following as well.

```suggestion
    ÃŽnterfaceIPAssignment entity defines four attributes: `router\_ip`,
```

2022-12-22 14:18 UTC, wouterdb commented on lsm-srlinux/README.md
> +-   The orchestrator will then install the project;
```suggestion
-   install the project
```

2022-12-23 08:24 UTC, wouterdb approved these changes

2022-12-23 08:24 UTC, wouterdb commented on lsm-srlinux/README.md
> +**Python version 3.9**, Docker, Containerlab and Inmanta need to be installed on your machine and our examples repository has to be cloned in order to proceed. Please make sure to follow the links be
```suggestion
**Python version 3.9**, needs to be installed on your machine.
```

2022-12-23 08:24 UTC, wouterdb commented on lsm-srlinux/README.md
> +5.  Change the \<token\> in the repo url to the credentials to the package repository that you received.
```suggestion
5.  Change the \<token\> in the repo url to the credentials to the package repository (see Prerequisites section).
```

2022-12-23 08:48 UTC, merged