Issue/1519 run against rc 2
inmanta/examples pull request #41
Opened 2023-03-27 10:37 UTC by FloLey

Add option to run the OSS quickstart to a specific version in jenkins

Closes inmanta/irt#1519

2023-03-27 14:36 UTC, arnaudsjs requested changes

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +def update_topology() {
This method can use a docstring

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +    def version = env.rc_version
Did you test this file?

```suggestion
    def version = env.version
```

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +                            ci/do_test_deployment_and_verify.sh ${rc_version}
```suggestion
                            ci/do_test_deployment_and_verify.sh ${version}
```

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +        string(name: 'version', description: 'Run OSS quickstart against the specified version. If left empty it will run against the stable version.\nThe version can be of format 2023.1.1rc202302171
```suggestion
        string(name: 'version', description: 'Run OSS quickstart against the specified version. If left empty it will run against the latest stable version.\nThe version can be of format 2023.1.1rc20230217144359, 2023.1.1rc or 2023.1.1')
```

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +    return
```suggestion
    return 'latest'
```

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +            error("Invalid version format: ${version}")
What does this line do? I was expecting:

```
throw new Exception("Invalid version format: ${version}")
```

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +        def matcher = version =~ /(\d{4})\.(\d+)\.(\d+)(rc)?(\d*)/
The versioning of OSS is as followed:

* First release of the year: `<year>.1`
* Patch releases add a third digit: `<year>.1.1`
* A minor release increments the second digit: `<year>.2`

(See: https://pypi.org/project/inmanta/#history)

This regex will fail when the version number only has two digits.

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +def formatVersion() {
```suggestion
def convert_python_version_to_docker_tag() {
```

2023-03-27 14:36 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +        string(name: 'version', description: 'Run OSS quickstart against the specified version. If left empty it will run against the stable version.\nThe version can be of format 2023.1.1rc202302171
I would explicitly mention here that this parameter expects the version of the Python package of the OSS product.

2023-03-27 14:45 UTC, FloLey commented on Networking/SR Linux/ci/Jenkinsfile
> +        string(name: 'version', description: 'Run OSS quickstart against the specified version. If left empty it will run against the stable version.\nThe version can be of format 2023.1.1rc202302171
No I don't think so, is it is left empty it follows the old path.

2023-03-27 14:48 UTC, FloLey commented on Networking/SR Linux/ci/Jenkinsfile
> +    return
this is not really needed as it is the default value in the topology file. and the update function only updates if this function returns something. Do you still prefer to always update the topology file?

2023-03-27 14:50 UTC, FloLey commented on Networking/SR Linux/ci/Jenkinsfile
> +            error("Invalid version format: ${version}")
it does this: https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#error-error-signal

2023-03-27 14:51 UTC, FloLey commented on Networking/SR Linux/ci/Jenkinsfile
> +    def version = env.rc_version
yes I did. I decided to rename it at the last moment but forgot to rename it at all the other locations. sorry about that

2023-03-28 06:04 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +        string(name: 'version', description: 'Run OSS quickstart against the specified version. If left empty it will run against the stable version.\nThe version can be of format 2023.1.1rc202302171
I thought the cron job trigger would fail when there is no default value set, but if it doesn't then there isn't an issue.

2023-03-28 06:08 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +            error("Invalid version format: ${version}")
Cool! I didn't know about that feature. I was mainly surprised by the return statement of this `error()` call, but I see you removed it as it is unreachable code.

2023-03-28 06:14 UTC, arnaudsjs requested changes

2023-03-28 06:14 UTC, arnaudsjs commented on Networking/SR Linux/ci/Jenkinsfile
> +    """
This is a Python style comment. That's not going to work in Groovy, is it?

2023-03-28 07:21 UTC, FloLey commented on Networking/SR Linux/ci/Jenkinsfile
> +        string(name: 'version', description: 'Run OSS quickstart against the specified version. If left empty it will run against the stable version.\nThe version can be of format 2023.1.1rc202302171
Is there a difference in how the build is triggered by the cron job or by a new commit? If there is I'll change it just to be sure, otherwise there is no issue.

2023-03-28 08:30 UTC, arnaudsjs approved these changes

2023-03-28 09:27 UTC, Hugo-Inmanta approved these changes

2023-03-28 09:52 UTC, merged