Add testing pipeline for new lsm quickstart
inmanta/examples pull request #43
Opened 2023-03-30 09:10 UTC by arnaudsjs

Closes inmanta/inmanta-core#5513

2023-03-30 09:33 UTC, FloLey approved these changes

2023-03-31 08:55 UTC, sanderr requested changes

2023-03-31 08:55 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +* @param pythonVersion: The python version of the inmanta-service-orchestrator package of the orchestrator we are running against.
I find this name to be very confusing. It took me a while to realize this is the version of the `inmanta-service-orchestrator` Python package (e.g. `6.0.0`) rather than the Python version (e.g. `3.9`).

2023-03-31 08:55 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +    yamlDct['repo'][1]['url'] = "https://packages.inmanta.com/${token}/inmanta-service-orchestrator-${majorVersion}-stable/python/simple/"
Ideally I think we should test against appropriately constrained GitHub versions but we don't have a good mechanism for that. inmanta/web-console#4750 describes the same issue for the front-end tests. Perhaps we should see if we can address inmanta/irt#981 sometime soon. I'll add links to here and the web-console ticket.

2023-03-31 08:55 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +            formattedVersion += "-${rc}"
Do these timestamps actually match?

2023-03-31 08:55 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +        parameterizedCron(BRANCH_NAME == 'master' ? "H H(2-5) * * * %version=6" : "")
Don't we want the nightlies to run against dev?

2023-03-31 08:55 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +    def matcher = pythonVersion =~ /(\d+)/
Could be interesting (and simple) to support `6rc` as well?

2023-03-31 08:55 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +                                pip install --pre pytest-inmanta-extensions "inmanta-service-orchestrator==${version}"
```suggestion
                                pip install --pre inmanta-core[pytest-inmanta-extensions] "inmanta-service-orchestrator==${version}"
```
This should ensure we get the matching `pytest-inmanta-extensions` version without having to backtrack too much.

2023-03-31 08:55 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +                                pip install pytest-inmanta-extensions inmanta-service-orchestrator
```suggestion
                                pip install inmanta-core[pytest-inmanta-extensions] inmanta-service-orchestrator
```

2023-03-31 08:55 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +                                pip install --pre pytest-inmanta-extensions "inmanta-service-orchestrator==${version}"
Why `--pre` if we have an explicit version? Did you mean to add this in the `else` clause instead?

2023-03-31 09:26 UTC, arnaudsjs commented on lsm-srlinux/ci/Jenkinsfile
> +            formattedVersion += "-${rc}"
The docker images don't have a timestamp, they just have the `-rc` part. I will make that more clear by not doing the variable substitution.

2023-03-31 09:27 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +            formattedVersion += "-${rc}"
Ah, I now see you only captured the `rc` part.

2023-03-31 09:33 UTC, arnaudsjs commented on lsm-srlinux/ci/Jenkinsfile
> +    def matcher = pythonVersion =~ /(\d+)/
This RC version feature is something that will be used at release time. In that situation, I think it's better to use explicit version numbers to make sure that we are running the tests against exactly the version we want to use.

2023-03-31 09:48 UTC, arnaudsjs commented on lsm-srlinux/ci/Jenkinsfile
> +                                pip install --pre pytest-inmanta-extensions "inmanta-service-orchestrator==${version}"
Indeed. I think it's not strictly required. I will remove it.

2023-03-31 09:51 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +    def matcher = pythonVersion =~ /(\d+)/
Ok, fine by me

2023-04-04 07:50 UTC, sanderr requested changes

2023-04-04 07:50 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +        string(name: 'version', defaultValue: '6dev', description: 'Run the lsm quickstart against the specified version of ISO product. The version can be of format 6.1.1rc20230217144359, 6.1.1rc, 6
```suggestion
        string(name: 'version', defaultValue: '7dev', description: 'Run the lsm quickstart against the specified version of ISO product. The version can be of format 6.1.1rc20230217144359, 6.1.1rc, 6.1.1, 6 or 6dev.')
```
If we run against dev, doesn't 7dev make the most sense? Not too strong of an opinion, I think it all ties in with the more broader issue of what we should test against which versions. Ideally we'd test against all of them but we can't realistically make everything a matrix build... So we need to address this at some point but for now I'm fine with any of the logical choices.

2023-04-04 07:50 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +        parameterizedCron(BRANCH_NAME == 'master' ? "H H(2-5) * * * %version=6dev" : "")
```suggestion
        parameterizedCron(BRANCH_NAME == 'master' ? "H H(2-5) * * * %version=7dev" : "")
```
Same question here

2023-04-04 07:50 UTC, sanderr commented on lsm-srlinux/ci/Jenkinsfile
> +                                pip install --pre "inmanta-core[pytest-inmanta-extensions]" "inmanta-service-orchestrator~=${major_version}.0"
```suggestion
                                pip install "inmanta-core[pytest-inmanta-extensions]" "inmanta-service-orchestrator~=${major_version}.0.dev"
```
I think this is safer: it's what we want and nothing more. `--pre` allows everything (including external) packages to be a pre-release. I think we should avoid it whenever possible.

2023-04-05 13:37 UTC, sanderr approved these changes

2023-04-05 13:39 UTC, merged