Add vendor configuration examples
inmanta/examples pull request #5
Opened 2021-12-21 15:13 UTC by Pouriya-Inmanta

# Description

Adds device configuration examples for supported vendors using the `Inmanta` language.

- [ ] Cisco
- [ ] Juniper
- [ ] Nokia

2021-12-22 09:38 UTC, wouterdb reviewed
1. nice! (and fast)
2. some of the readmes are empty
3. I have some question, I don't necessarily think these things should change, but I just want to know what/why

2021-12-22 09:38 UTC, wouterdb commented on vendors/Cisco/IP Address/ip_address.cf
> +# Approach A - De-coupling IP address configuration with the interface
I don't know if we should show both or only one? 

- all in a uniform style may create less confusion?
- this teaches one more thing

2021-12-22 09:38 UTC, wouterdb commented on vendors/Cisco/README.md
> +The provided examples in the `main.cf` file can be applied on a device using [containerlab](https://containerlab.srlinux.dev/) using the provided topology file.
1. I don't see the topology file?
2. I would write out the exact commands to apply it (and perhaps even how to check if it is applied on the device)

2021-12-22 09:38 UTC, wouterdb commented on vendors/Cisco/IP Address/ip_address.cf
> +# import the Cisco module as an alias for easier access
1. why have separate folder with only one file in each folder?
2. if the file is not called main.cf, we may have to provide instructions on how to run it.

2021-12-22 09:38 UTC, wouterdb commented on vendors/Juniper/project.yml
> +    - https://github.com/inmanta/
This will require another module source to be able to check out the modules, but that requires an access token, I think that can do with some documentation as well.

2021-12-22 09:38 UTC, wouterdb commented on vendors/README.md
> +The OS of our choice for demonstrating these examples is a `Ubuntu`.
Why ubuntu? 

- common desktop OS
- common OS in the docker world
- not the Inmanta standard OS family?

2021-12-22 09:45 UTC, Pouriya-Inmanta commented on vendors/Cisco/IP Address/ip_address.cf
> +# Approach A - De-coupling IP address configuration with the interface
2. Yes, I will get to those when we start the work on their modules.
3. I have no preference here, we thought it could prepare them for examples in which this style becomes more apparent. e.g. the changes we made on Juniper and Juniper_services. However, if it causes confusion, we are better off removing them. 

What is the opinion of our other colleagues on point 3?

2021-12-22 09:50 UTC, pilferst commented on vendors/Cisco/IP Address/ip_address.cf
> +# Approach A - De-coupling IP address configuration with the interface
3. I think we can use both ways. Maybe it's better if we put it in different files.

2021-12-22 09:51 UTC, Pouriya-Inmanta commented on vendors/Cisco/README.md
> +The provided examples in the `main.cf` file can be applied on a device using [containerlab](https://containerlab.srlinux.dev/) using the provided topology file.
Its in the making

2021-12-22 11:51 UTC, Pouriya-Inmanta commented on vendors/README.md
> +The OS of our choice for demonstrating these examples is a `Ubuntu`.
Based on the discussion we had, I think we could continue with `Ubuntu`. If there are objections in the future, we can easily switch to another OS.

2021-12-22 12:48 UTC, Pouriya-Inmanta commented on vendors/Cisco/IP Address/ip_address.cf
> +# import the Cisco module as an alias for easier access
1. I will delete the folders and move the files to the project root directory (we can quite easily change these at this stage till we get the result we want).
2. Having all the examples in one `main.cf` file will be a little less intuitive IMO. Would that additional instruction be to just use the `-f` switch?

2021-12-22 21:06 UTC, bartv requested changes

2021-12-22 21:06 UTC, bartv commented on vendors/Cisco/README.md
> +The provided examples in the `*.cf` files can be applied on a router using [containerlab](https://containerlab.srlinux.dev/) using the provided [topology file](containerlab/topology.yml). It is needl
I am a bit confused that I am in the Cisco module and I need juniper and nokia images to test this?

2021-12-22 21:06 UTC, bartv commented on vendors/Cisco/ip_address.cf
> +interface3= c::Interface(
```suggestion
interface3 = c::Interface(
```

2021-12-22 21:06 UTC, bartv commented on vendors/Cisco/interface.cf
> +# import the Cisco module
Do we need to explain somewhere how they can push this to an orchestrator?

```bash
inmanta export -f interface.cf
```

2021-12-22 21:06 UTC, bartv commented on vendors/Cisco/README.md
> +The provided examples in the `*.cf` files can be applied on a router using [containerlab](https://containerlab.srlinux.dev/) using the provided [topology file](containerlab/topology.yml). It is needl
maybe create a single containerlab folder to which each vendor subdir points?

and have topology files that are single vendor, because someone will rarely have access to all 3 vendors

2022-01-03 08:35 UTC, Pouriya-Inmanta commented on vendors/Cisco/README.md
> +The provided examples in the `*.cf` files can be applied on a router using [containerlab](https://containerlab.srlinux.dev/) using the provided [topology file](containerlab/topology.yml). It is needl
yes, this is/was the initial stage. We needed to connect the Cisco interfaces to somewhere to apply the configs and it was cheaper to have a single LAB with three routers so that we could produce the examples without constantly changing the LAB topology. Once all is done, we can indeed convert it to a single vendor LAB.

2022-01-03 08:41 UTC, Pouriya-Inmanta commented on vendors/Cisco/interface.cf
> +# import the Cisco module
yes, I will include it.

Initially we implemented these examples using:

```
inmanta deploy ...
```

Do we show both ways?

2022-01-05 09:04 UTC, Pouriya-Inmanta commented on vendors/Juniper/project.yml
> +    - https://github.com/inmanta/
I added the documentation for this point.

2022-01-05 09:05 UTC, Pouriya-Inmanta commented on vendors/Cisco/README.md
> +The provided examples in the `*.cf` files can be applied on a router using [containerlab](https://containerlab.srlinux.dev/) using the provided [topology file](containerlab/topology.yml). It is needl
I added the single vendor topology files.

2022-01-12 11:57 UTC, bartv commented on vendors/Cisco/ip_address.cf
> +# Approach A - De-coupling IP address configuration with the interface
I see two issues with writing these two styles:

1. Are we sure that if we inspect the key-attributes and indexes style B still works?
2. We do not really explain that it is correct to write the same thing twice (if the indexes are correct that is).

2022-01-12 11:58 UTC, bartv commented on vendors/Cisco/ip_address.cf
> +# Approach A - De-coupling IP address configuration with the interface
(Applies of course to all examples)

2022-01-12 12:12 UTC, Pouriya-Inmanta commented on vendors/Cisco/ip_address.cf
> +# Approach A - De-coupling IP address configuration with the interface
1. I re-test and then deploy the entire example file with our examples on their respective routers and verify them on the routers to make sure they are `copy paste-able` for people who would like to give them a shot. In terms of them being applicable, they are.  But if it causes other issues, then we can resort to having a single one.
2. In this example, IP addresseses, interfaces, etc... are all different. the only thing they have in common is the router entity. Am I missing some other point?

2022-02-02 14:14 UTC, bartv commented on vendors/Cisco/README.md
> +After the successful deployment, from the machine running the `containerlab` you can SSH to each router using the default credentials `admin:admin`:
Is it admin:admin? For the xrv it was clab@123 so just checking to be sure.

2022-02-02 14:15 UTC, bartv commented on vendors/Cisco/interface_qos.cf
> +# Approach A - De-coupling configuration
There is only Approach A left. Can you also do a global search to see if there are any others left?

2022-02-02 14:16 UTC, Pouriya-Inmanta commented on vendors/Cisco/README.md
> +After the successful deployment, from the machine running the `containerlab` you can SSH to each router using the default credentials `admin:admin`:
yes.

2022-02-02 14:17 UTC, Pouriya-Inmanta commented on vendors/Cisco/interface_qos.cf
> +# Approach A - De-coupling configuration
will do.

2022-02-02 14:38 UTC, Pouriya-Inmanta commented on vendors/Cisco/interface_qos.cf
> +# Approach A - De-coupling configuration
Done

2022-02-02 14:40 UTC, bartv approved these changes

2022-02-03 13:02 UTC, wouterdb reviewed
1. I'm not convinced  that the folder name 'vendor' is the best option. `networking` or 'routers' might be  more descriptive name.

2022-02-03 13:15 UTC, Pouriya-Inmanta commented on vendors/Nokia/containerlab/topology.yml
> +      license: ./sros-20.7.R1.qcow2.license
it is a text file with `.license` extension.  
I do not know where it comes from though.

2022-02-03 13:20 UTC, Pouriya-Inmanta commented on vendors/Nokia/containerlab/topology.yml
> +      image: vrnetlab/vr-sros:20.10.R1
These are explained here https://github.com/inmanta/examples/blob/issue/Add_vendor_configuration_examples/vendors/Juniper/README.md?plain=1#L3

The tag will be how we name the image in the registry.

Do we need additional info?

2022-02-03 13:34 UTC, Pouriya-Inmanta commented on vendors/Cisco/README.md
> +The provided examples in the `*.cf` files can be applied on a `Cisco IOS-XR` router using [containerlab](https://containerlab.srlinux.dev/) with the provided [topology file](containerlab/topology.yml
I made the adjustments

2022-02-03 13:34 UTC, Pouriya-Inmanta commented on vendors/Cisco/README.md
> +Verify that the required `Docker` images are present:
I made the adjustments

2022-02-03 13:36 UTC, Pouriya-Inmanta commented on vendors/Cisco/interface_vrf.cf
> +    device=router,                              # Link the defined router
good suggestion

2022-02-03 13:40 UTC, Pouriya-Inmanta commented on vendors/Nokia/containerlab/topology.yml
> +      license: ./sros-20.7.R1.qcow2.license
Rename is done.

2022-02-07 08:39 UTC, wouterdb requested changes

2022-02-07 08:39 UTC, wouterdb commented on Networking/Cisco/README.md
> +If you do not see an output as depicted, it means you do not have those docker images present and need to acquire them from the vendor.
don't you need to build them using the containerlab scripts?

2022-02-07 08:39 UTC, wouterdb commented on Networking/Cisco/README.md
> +The provided examples in the `*.cf` files can be applied on `Cisco IOS-XR` devices either on a router that you have and by changing the IP address, hostname, etc... in the examples or by using [conta
I would make this a bulleted list.

2022-02-07 09:16 UTC, Pouriya-Inmanta commented on Networking/Cisco/README.md
> +If you do not see an output as depicted, it means you do not have those docker images present and need to acquire them from the vendor.
Addressed in the latest commit

2022-02-07 09:17 UTC, Pouriya-Inmanta commented on Networking/Cisco/README.md
> +The provided examples in the `*.cf` files can be applied on `Cisco IOS-XR` devices either on a router that you have and by changing the IP address, hostname, etc... in the examples or by using [conta
Addressed in the latest commit

2022-02-07 09:17 UTC, wouterdb approved these changes

2022-02-07 09:20 UTC, merged