[DUMMY]
inmanta/examples pull request #56
Opened 2023-10-17 07:23 UTC by Hugo-Inmanta

2023-10-17 09:54 UTC, sanderr approved these changes

2023-10-17 09:54 UTC, sanderr commented on Networking/SR Linux/ci/Jenkinsfile
> +                            python_version=$(docker inspect clab-srlinux-inmanta-server  | grep PYTHON_VERSION |  cut -d"=" -f2- | cut -d'"' -f1)
Cool! This is better than what I had in mind! Do you know where the env var comes from though? Can we rely on it?

2023-10-17 09:59 UTC, Hugo-Inmanta commented on Networking/SR Linux/ci/Jenkinsfile
> +                            python_version=$(docker inspect clab-srlinux-inmanta-server  | grep PYTHON_VERSION |  cut -d"=" -f2- | cut -d'"' -f1)
I think it is set here https://github.com/inmanta/irt/blob/7bebdec6640558cd66630fa379c1cf47ba3a13ef/irt/release/build_docker_image.py#L280

2023-10-17 10:32 UTC, arnaudsjs requested changes

2023-10-17 10:32 UTC, arnaudsjs commented on lsm-srlinux/ci/Jenkinsfile
> +                            python_version=$(docker inspect clab-srlinux-inmanta-server  | grep PYTHON_VERSION |  cut -d"=" -f2- | cut -d'"' -f1)
I like it, but I am wondering whether it works correctly. I tried this command on an iso7 docker images that was present on my system and I get two times the version number:

```
$ python_version=$(docker inspect 4dc3990f106c | grep PYTHON_VERSION | cut -d"=" -f2- | cut -d'"' -f1)
$ echo ${python_version}
3.9
3.9
```

Did you test this?

2023-10-17 14:38 UTC, Hugo-Inmanta commented
Tested against
- [network-quickstart - latest](https://jenkins.inmanta.com/job/integration-tests/job/network-quickstart/job/issue%252F188-jenkinsfile-test-branch/12/)
- [network-quickstart - 2023.1](https://jenkins.inmanta.com/job/integration-tests/job/network-quickstart/job/issue%252F188-jenkinsfile-test-branch/15/parameters/)
- [quickstart-lsm - dev7](https://jenkins.inmanta.com/job/integration-tests/job/quickstart-lsm/job/issue%252F188-jenkinsfile-test-branch/7/parameters/)

2023-10-17 14:46 UTC, sanderr approved these changes

2023-10-18 06:03 UTC, arnaudsjs approved these changes

2023-10-18 06:23 UTC, merged