[FIX] remove overriding default value in chron expression
inmanta/examples pull request #57
Opened 2023-10-23 09:15 UTC by Hugo-Inmanta

Closes https://github.com/inmanta/inmanta-core/issues/6626

2023-10-23 13:10 UTC, Hugo-Inmanta commented
Tested with parameter version==6 here: https://jenkins.inmanta.com/job/integration-tests/job/quickstart-lsm/job/issue%252F6626-quickstart-lsm-nightly-runs-against-iso6/8/consoleText
The latest `inmanta-service-orchestrator`==6.4.0 is correctly used

2023-10-25 07:40 UTC, arnaudsjs requested changes

2023-10-25 07:42 UTC, arnaudsjs requested changes

2023-10-25 07:42 UTC, arnaudsjs commented on lsm-srlinux/ci/Jenkinsfile
> +                            echo "inm_version=$inmanta_version"
Why abbreviate debugging output:
```suggestion
                            echo "inmanta_version=$inmanta_version"
```

2023-10-26 07:47 UTC, arnaudsjs approved these changes

2023-10-26 08:37 UTC, merged