199/allow specifying rc version
inmanta/examples pull request #64
Opened 2023-12-29 16:47 UTC by FloLey

2024-01-02 16:06 UTC, sanderr requested changes

2024-01-02 16:06 UTC, sanderr commented on Networking/SR Linux/ci/Jenkinsfile
> +                                elif [[ $version =~ [0-9]{4}\\.[0-9]rc[0-9]{14}$ ]]; then
I see that it's more complicated for OSS than for iso because we have 2-digit version numbers in most cases. I'm not sure we can model the same behavior as for iso in a simple and intuitive way. I would propose we just don't try. I think we can greatly simplify these conditions if we just drop the "Allow unspecified digits to float, e.g., 6 -> ~=6.0" branch. Then we don't have to check this condition here, nor the `*.*.*` one. We just get the rc case, the dev case and the else case (with `==`).

2024-01-02 16:11 UTC, FloLey commented on Networking/SR Linux/ci/Jenkinsfile
> +        def matcher = version =~ /(\d{4})\.(\d+)(\.\d+)?(rc\d*)?(\.dev\d*)?/
I just wanted to have a regex that matches only what we accept as inputs and nothing else.
`def dev = matcher.group(5) ?: ""` can be removed, I used it to test the regex and forgot to remove it afterwards

2024-01-02 16:25 UTC, sanderr commented on Networking/SR Linux/ci/Jenkinsfile
> +        def matcher = version =~ /(\d{4})\.(\d+)(\.\d+)?(rc\d*)?(\.dev\d*)?/
I see, fine by me then.

2024-01-04 13:03 UTC, sanderr approved these changes

2024-01-04 13:40 UTC, merged