Issue/add integration module example
inmanta/examples pull request #69
Opened 2024-03-25 16:22 UTC by edvgui

Add an example of integration module, defining two lsm services, and the typical test cases to cover them.

2024-03-26 09:01 UTC, sanderr commented on lsm-testing/.ci-integration-tests.yml
Is this supposed to serve as an example as well? It's meaningless without the Jenkinsfile, isn't it?

2024-03-26 09:08 UTC, edvgui commented on lsm-testing/.ci-integration-tests.yml
I am not sure to be honest.  My main goal was to have a ci that can be used to make sure this example works.  It think it does also serve a documentation purpose for internal user as this is how we configure the cis of our modules.  But it is indeed not useful on its own for external users.  For ci documentation, I would prefer not to propose any "public guidelines", firstly because it depends highly on the infra of the developer, and secondly because we use Jenkins, which is not at all the type of hot tech that people want to move to (imo).

2024-03-26 09:12 UTC, sanderr commented on lsm-testing/.ci-integration-tests.yml
Ok, good arguments. As long as it's clear from the to-be-added documentation that this file (and perhaps others?) is not part of the guideline per se, I have no objections.

2024-03-26 13:10 UTC, wouterdb commented on lsm-testing/README.md
> +installed. If you don't, you can replace it with `python3 -m venv .env && source .env/bin/activate`.
I would just explain how to install ``virtualenvwrapper`` or link to its install docs. (i.e. go for maximal copy-paste-ability)

2024-03-26 13:12 UTC, wouterdb commented on lsm-testing/inmanta_plugins/integration_example/config.py
> +import inmanta_plugins.config.const
Do we need this?

2024-03-26 13:40 UTC, edvgui commented on lsm-testing/inmanta_plugins/integration_example/config.py
> +import inmanta_plugins.config.const
We use that module below, or am I not understanding your question correctly?

2024-03-26 13:41 UTC, wouterdb requested changes
Very nice

2024-03-26 13:41 UTC, wouterdb commented on lsm-testing/inmanta_plugins/integration_example/config.py
> +"""
```suggestion

This module validates and parses the config file using pydantic
"""
```

2024-03-26 13:41 UTC, wouterdb commented on lsm-testing/model/services/important_customer/lsm.cf
> +        serviceId=lsm::allocators::get_first_free_integer(
I would link to allocation v3 docs here (when they exist)

2024-03-26 13:41 UTC, wouterdb commented on lsm-testing/tests/test_basics.py
> +    project.compile(
```suggestion
    """
    This test only checks if the code compiles correctly.
    
    It is the most basic test possible, it doesn't test a lot, but it is fast.
    """
    project.compile(
```

2024-03-26 15:31 UTC, edvgui commented on lsm-testing/README.md
> +## Running tests
Done in https://github.com/inmanta/examples/pull/69/commits/f99bc898fbef377591574459b5364e10948f6982

2024-03-26 15:32 UTC, edvgui commented on lsm-testing/tests/test_model/test_all_services.py
> +    # Make a full compile to validate all our services can work together
Here is another type of interference, we check that the two services can be used together, does it really hurt to do that additional compile?

2024-03-26 15:33 UTC, edvgui commented on lsm-testing/tests/test_lsm/test_basic_service_lsm.py
> +async def service_lifecycle(
Done in https://github.com/inmanta/examples/pull/69/commits/f99bc898fbef377591574459b5364e10948f6982.  I added a docstring to explain the goal of the helper function, and mentioned the "sequential" approach in a comment next to a parameter that allows to toggle on that approach easily

2024-03-26 15:33 UTC, edvgui commented on lsm-testing/tests/test_basics.py
> +def test_basics(project: Project) -> None:
There is still a point, I tried to explain it in https://github.com/inmanta/examples/pull/69/commits/f99bc898fbef377591574459b5364e10948f6982.  Is it clear enough?

2024-03-26 15:33 UTC, edvgui commented on lsm-testing/tests/test_basics.py
> +    project.compile(
Part of https://github.com/inmanta/examples/pull/69/commits/f99bc898fbef377591574459b5364e10948f6982

2024-03-26 15:42 UTC, edvgui commented on lsm-testing/tests/test_model/test_basic_service_partial_compile.py
> +    any of the rules set by the orchestrator.
Done in https://github.com/inmanta/examples/pull/69/commits/5ccc9384c5bef03a63cb15c55e643acb47a3aba3

2024-03-26 15:43 UTC, edvgui commented on lsm-testing/inmanta_plugins/integration_example/config.py
> +"""
Done in https://github.com/inmanta/examples/pull/69/commits/5ccc9384c5bef03a63cb15c55e643acb47a3aba3

2024-03-26 15:43 UTC, edvgui commented on lsm-testing/README.md
> +installed. If you don't, you can replace it with `python3 -m venv .env && source .env/bin/activate`.
Done in https://github.com/inmanta/examples/pull/69/commits/f99bc898fbef377591574459b5364e10948f6982

2024-03-27 10:30 UTC, wouterdb approved these changes

2024-03-28 15:10 UTC, sanderr reviewed
I'm not sure how far I'll get this week so I'll just release comments as I go through rather than all at once.

2024-03-29 11:00 UTC, sanderr commented on lsm-testing/README.md
> +import integration_example::services::basic::lsm
Isn't the first line redundant? Or do we do it differently than Python?

2024-04-05 07:48 UTC, sanderr commented on lsm-testing/README.md
> +The services defined in the model offer a file-based interface to customize their behavior.  You should provide the file named `integration-example-config.yml` inside of the `files` folder of your pr
This is not typically how an integration module would be configured, is it? I think it's fine to take some shortcuts for the sake of the example, but where we do we should probably mention it. So we don't give the impression that this is a typical usage / best practice.

2024-04-05 07:50 UTC, sanderr commented on lsm-testing/README.md
> +The test suite of this module cover most of the good weather scenarios for our service, and some of the bad weather ones.  The test suite does the following:
I think I understand what you mean, but I've never heard these terms before in this context. Feels slightly out of place to me, but it's probably clear what you mean.

2024-04-05 07:55 UTC, sanderr commented on lsm-testing/README.md
> +Some tests run locally only, and some run on a real, remote, orchestrator.  Too test all these scenarios, we heavily rely on the `pytest-inmanta-lsm` library, which is meant to make testing of such i
```suggestion
Some tests run locally only, and some run on a real, remote, orchestrator. To test all these scenarios, we heavily rely on the `pytest-inmanta-lsm` library, which is meant to make testing of such integration modules easy and reliable.
```

2024-04-05 07:58 UTC, sanderr commented on lsm-testing/README.md
> +This module illustrate the typical test coverage you want when developing an integration module.  Here are the different types of test it includes:
```suggestion
This module illustrates the typical test coverage you want when developing an integration module.  Here are the different types of test it includes:
```

2024-04-05 07:59 UTC, sanderr commented on lsm-testing/README.md
> +1. Mocked test: fast test, that don't deploy any resources, but only compile the model and verify it is as expected. Uses the [lsm_project fixture](https://github.com/inmanta/pytest-inmanta-lsm?tab=r
*If* we rename the `lsm_project` fixture, we should use the new name here.

2024-04-05 09:43 UTC, sanderr commented on lsm-testing/tests/test_basics.py
> +    2. We are making sure that this modules can be used by another module,
```suggestion
    2. We are making sure that this module can be used by another module,
```

2024-04-05 09:43 UTC, sanderr commented on lsm-testing/tests/test_model/test_basic_service_allocation.py
> +    # Assert that all services have a different serviceId
Should we also assert they're within the configured range?

2024-04-05 09:43 UTC, sanderr commented on lsm-testing/tests/test_model/test_basic_service_partial_compile.py
> +    # Create an add services to our inventory
```suggestion
    # Create and add services to our inventory
```

2024-04-05 09:43 UTC, sanderr commented on lsm-testing/tests/test_model/test_basic_service_partial_compile.py
> +        for i in range(0, 2)
```suggestion
        for i in range(2)
```

2024-04-05 09:43 UTC, sanderr commented on lsm-testing/tests/test_model/test_important_customer_service_partial_compile.py
> +        lsm_project.post_partial_compile_validation(
It's also important that the shared resources are the same for each of these compiles. But perhaps that is tested in the real orchestrator tests?

2024-04-05 09:43 UTC, sanderr commented on lsm-testing/tests/test_lsm/test_import_customer_service_lsm.py
This does not test anything about deployment. Shouldn't it?

2024-04-05 09:43 UTC, sanderr commented on lsm-testing/inmanta_plugins/integration_example/services/important_customer/lsm.py
> +    previous_attributes = (
I wonder if we could generalize this whole thing in lsm, all in the model:
1. attach the current lifecycle state to the instance
2. derive relations between the lifecycle states, and possibly model the edges explicitly
3. derive `previous_state_attribute_set` from the type of edge, its operation, and whether it was a success or an error transfer.

Just food for thought. Still large chunks missing.

2024-04-15 08:04 UTC, edvgui commented on lsm-testing/tests/test_model/test_important_customer_service_partial_compile.py
> +        lsm_project.post_partial_compile_validation(
It is being tested by this check `post_partial_compile_validation` checks that the shared resources are never modified

2024-04-15 08:04 UTC, edvgui commented on lsm-testing/inmanta_plugins/integration_example/services/important_customer/lsm.py
> +from inmanta_plugins.lsm import allocation_helpers  # type: ignore
Because the lsm module is a v1 module, so it doesn't contain a `py.typed` file

2024-04-15 08:07 UTC, edvgui commented on lsm-testing/tests/test_lsm/test_import_customer_service_lsm.py
I am not sure.  Typically these test will assert that the full service works end-to-end, which for network services, is very often a simple connectivity check.  But for the mock services here, we can not really make such global assertion.  And check that each resource is deployed is very cumbersome.

2024-04-15 08:10 UTC, sanderr commented on lsm-testing/tests/test_model/test_important_customer_service_partial_compile.py
> +        lsm_project.post_partial_compile_validation(
Ok, for some reason I assumed we just checked the ids of the resources, not their attributes.

2024-04-15 08:12 UTC, sanderr commented on lsm-testing/tests/test_lsm/test_import_customer_service_lsm.py
That makes sense, but as it is I fear it might give the impression that what is presented here is the full extent of what we recommend you to test. So I would at least at a comment, or a not in the readme, that typically you would also add an end-to-end test, but that that makes little sense in the context of this simple example.

2024-04-15 08:18 UTC, edvgui commented on lsm-testing/README.md
> +The services defined in the model offer a file-based interface to customize their behavior.  You should provide the file named `integration-example-config.yml` inside of the `files` folder of your pr
Yes, that is how we expose a configurable interface for the module (we could have made the user write the same type of input in the model, but yaml is less scary for people that don't know inmanta DSL)

2024-04-15 08:23 UTC, edvgui commented on lsm-testing/README.md
> +1. Mocked test: fast test, that don't deploy any resources, but only compile the model and verify it is as expected. Uses the [lsm_project fixture](https://github.com/inmanta/pytest-inmanta-lsm?tab=r
Not really, we really don't do much more than that.  We have some helper which allows to also do promote/rollback operations, or perform auto transfers.  But there is no logic to mock the resource deployment, so we can not reuse the full logic of the server

2024-05-03 13:29 UTC, sanderr approved these changes

2024-05-03 13:39 UTC, merged